// controller/src/app/app.component.ts
import { Component, signal, computed } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ConnectionService, ConnectionStatus } from './core/services/connection.service';
import { InputService } from './core/services/input.service';
import { BindingsService, DigitalInput } from './core/services/bindings.service';
import { VirtualJoystickComponent, JoystickPosition } from './shared/components/virtual-joystick/virtual-joystick.component';
import { PresetPanelComponent } from './shared/components/preset-panel/preset-panel.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive, VirtualJoystickComponent, PresetPanelComponent],
  template: `
    <div class="h-screen flex flex-col">
      <!-- Header -->
      <header class="bg-saint-surface border-b border-saint-surface-light px-4 py-3 flex items-center justify-between">
        <nav class="flex gap-2">
          @if (!presetPanelActive()) {
            <a routerLink="/controller" routerLinkActive="bg-saint-primary"
               class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors">
              Controller
            </a>
            <a routerLink="/bindings" routerLinkActive="bg-saint-primary"
               class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors">
              Bindings
            </a>
            <a routerLink="/settings" routerLinkActive="bg-saint-primary"
               class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors">
              Settings
            </a>
          } @else {
            <button (click)="bindingsService.hidePanel()"
                    class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors flex items-center gap-2">
              <span class="material-icons text-sm">arrow_back</span>
              Back
            </button>
          }
        </nav>

        <div class="flex items-center gap-4">
          <!-- Connection Status -->
          <div class="flex items-center gap-2">
            <div [class]="getStatusClass()"></div>
            <span class="text-sm text-saint-text-muted">{{ getStatusText() }}</span>
          </div>

          <!-- E-Stop Button -->
          <button
            (click)="emergencyStop()"
            class="flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-colors uppercase tracking-wide"
            title="Emergency Stop">
            <span class="material-icons icon-sm">front_hand</span>
            <span>E-Stop</span>
          </button>
        </div>
      </header>

      <!-- Main Content - shows either router outlet or preset panel -->
      <main class="flex-1 overflow-hidden">
        @if (presetPanelActive()) {
          <app-preset-panel></app-preset-panel>
        } @else {
          <div class="h-full overflow-auto">
            <router-outlet></router-outlet>
          </div>
        }
      </main>

      <!-- Footer Navigation Bar -->
      <footer class="bg-saint-surface border-t border-saint-surface-light">
        <!-- Tab Buttons -->
        <div class="flex border-b border-saint-surface-light">
          <button
            (click)="togglePanel('controls')"
            [class]="getTabClass('controls')"
            class="flex items-center gap-2 px-4 py-2 text-sm transition-colors">
            <span class="material-icons icon-sm">sports_esports</span>
            <span>Controls</span>
            @if (gamepadConnected()) {
              <span class="px-2 py-0.5 bg-saint-success/20 text-saint-success text-xs rounded-full">
                {{ gamepadName() }}
              </span>
            } @else {
              <span class="px-2 py-0.5 bg-saint-text-muted/20 text-saint-text-muted text-xs rounded-full">
                No Controller
              </span>
            }
            <span class="material-icons icon-sm transition-transform"
                  [class.rotate-180]="activePanel() === 'controls'">
              expand_less
            </span>
          </button>
        </div>

        <!-- Sliding Panel -->
        <div class="overflow-hidden transition-all duration-300 ease-in-out"
             [style.height]="activePanel() ? '280px' : '0'">

          <!-- Controls Panel -->
          @if (activePanel() === 'controls') {
            <div class="p-4 h-full">
              <div class="flex justify-center items-center h-full">
                <!-- Virtual Controller Layout -->
                <div class="relative w-full max-w-2xl h-56">

                  <!-- Left Side -->
                  <div class="absolute left-0 top-0 bottom-0 w-1/2 flex flex-col justify-between py-2">
                    <!-- Left Shoulder/Trigger -->
                    <div class="flex flex-col gap-1 ml-8">
                      <button class="w-20 h-6 rounded-t-lg text-xs font-medium transition-colors relative overflow-hidden"
                              [class.bg-saint-surface-light]="leftTrigger() < 0.1"
                              [class.bg-saint-primary]="leftTrigger() >= 0.1">
                        <div class="absolute inset-0 bg-saint-primary transition-all"
                             [style.width.%]="leftTrigger() * 100"></div>
                        <span class="relative z-10">LT</span>
                      </button>
                      <button class="w-20 h-5 rounded-b text-xs font-medium transition-colors active:scale-95"
                              [class.bg-saint-surface-light]="!gamepadButtons()['LB'] && !virtualPressed()['lb']"
                              [class.bg-saint-primary]="gamepadButtons()['LB'] || virtualPressed()['lb']"
                              (click)="onVirtualButtonPress('lb')">
                        LB
                      </button>
                    </div>

                    <!-- Left Stick and D-Pad Row -->
                    <div class="flex items-center gap-6 ml-4">
                      <!-- Left Analog Stick -->
                      <app-virtual-joystick
                        [size]="80"
                        [knobSize]="40"
                        [externalPosition]="physicalLeftStick()"
                        (positionChange)="onLeftStickChange($event)">
                      </app-virtual-joystick>

                      <!-- D-Pad -->
                      <div class="relative w-20 h-20">
                        <!-- Up -->
                        <button class="absolute top-0 left-1/2 -translate-x-1/2 w-6 h-6 rounded-t transition-colors active:scale-95"
                                [class.bg-saint-primary]="gamepadButtons()['DPadUp'] || virtualPressed()['d_pad_up']"
                                [class.bg-saint-surface-light]="!gamepadButtons()['DPadUp'] && !virtualPressed()['d_pad_up']"
                                (click)="onVirtualButtonPress('d_pad_up')">
                          <span class="material-icons text-sm">keyboard_arrow_up</span>
                        </button>
                        <!-- Down -->
                        <button class="absolute bottom-0 left-1/2 -translate-x-1/2 w-6 h-6 rounded-b transition-colors active:scale-95"
                                [class.bg-saint-primary]="gamepadButtons()['DPadDown'] || virtualPressed()['d_pad_down']"
                                [class.bg-saint-surface-light]="!gamepadButtons()['DPadDown'] && !virtualPressed()['d_pad_down']"
                                (click)="onVirtualButtonPress('d_pad_down')">
                          <span class="material-icons text-sm">keyboard_arrow_down</span>
                        </button>
                        <!-- Left -->
                        <button class="absolute left-0 top-1/2 -translate-y-1/2 w-6 h-6 rounded-l transition-colors active:scale-95"
                                [class.bg-saint-primary]="gamepadButtons()['DPadLeft'] || virtualPressed()['d_pad_left']"
                                [class.bg-saint-surface-light]="!gamepadButtons()['DPadLeft'] && !virtualPressed()['d_pad_left']"
                                (click)="onVirtualButtonPress('d_pad_left')">
                          <span class="material-icons text-sm">keyboard_arrow_left</span>
                        </button>
                        <!-- Right -->
                        <button class="absolute right-0 top-1/2 -translate-y-1/2 w-6 h-6 rounded-r transition-colors active:scale-95"
                                [class.bg-saint-primary]="gamepadButtons()['DPadRight'] || virtualPressed()['d_pad_right']"
                                [class.bg-saint-surface-light]="!gamepadButtons()['DPadRight'] && !virtualPressed()['d_pad_right']"
                                (click)="onVirtualButtonPress('d_pad_right')">
                          <span class="material-icons text-sm">keyboard_arrow_right</span>
                        </button>
                        <!-- Center -->
                        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-6 h-6 bg-saint-surface-light"></div>
                      </div>
                    </div>

                    <!-- Spacer -->
                    <div class="h-6"></div>
                  </div>

                  <!-- Right Side -->
                  <div class="absolute right-0 top-0 bottom-0 w-1/2 flex flex-col justify-between py-2">
                    <!-- Right Shoulder/Trigger -->
                    <div class="flex flex-col gap-1 ml-auto mr-8">
                      <button class="w-20 h-6 rounded-t-lg text-xs font-medium transition-colors relative overflow-hidden"
                              [class.bg-saint-surface-light]="rightTrigger() < 0.1"
                              [class.bg-saint-primary]="rightTrigger() >= 0.1">
                        <div class="absolute inset-0 bg-saint-primary transition-all origin-right"
                             [style.width.%]="rightTrigger() * 100"></div>
                        <span class="relative z-10">RT</span>
                      </button>
                      <button class="w-20 h-5 rounded-b text-xs font-medium transition-colors active:scale-95"
                              [class.bg-saint-surface-light]="!gamepadButtons()['RB'] && !virtualPressed()['rb']"
                              [class.bg-saint-primary]="gamepadButtons()['RB'] || virtualPressed()['rb']"
                              (click)="onVirtualButtonPress('rb')">
                        RB
                      </button>
                    </div>

                    <!-- Face Buttons and Right Stick Row -->
                    <div class="flex items-center gap-6 justify-end mr-4">
                      <!-- Face Buttons (ABXY) -->
                      <div class="relative w-20 h-20">
                        <!-- Y (top) - Opens Moods panel -->
                        <button class="absolute top-0 left-1/2 -translate-x-1/2 w-8 h-8 rounded-full text-xs font-bold transition-colors shadow-md active:scale-90"
                                [class.bg-yellow-400]="gamepadButtons()['Y'] || virtualPressed()['y']"
                                [class.bg-yellow-600]="!gamepadButtons()['Y'] && !virtualPressed()['y']"
                                [class.scale-95]="gamepadButtons()['Y'] || virtualPressed()['y']"
                                (mousedown)="onVirtualButtonDown('y')"
                                (mouseup)="onVirtualButtonUp('y')"
                                (mouseleave)="onVirtualButtonUp('y')"
                                (touchstart)="onVirtualButtonDown('y'); $event.preventDefault()"
                                (touchend)="onVirtualButtonUp('y')">
                          Y
                        </button>
                        <!-- A (bottom) - Select -->
                        <button class="absolute bottom-0 left-1/2 -translate-x-1/2 w-8 h-8 rounded-full text-xs font-bold transition-colors shadow-md active:scale-90"
                                [class.bg-green-400]="gamepadButtons()['A'] || virtualPressed()['a']"
                                [class.bg-green-600]="!gamepadButtons()['A'] && !virtualPressed()['a']"
                                [class.scale-95]="gamepadButtons()['A'] || virtualPressed()['a']"
                                (click)="onVirtualButtonPress('a')">
                          A
                        </button>
                        <!-- X (left) - Opens Animations panel -->
                        <button class="absolute left-0 top-1/2 -translate-y-1/2 w-8 h-8 rounded-full text-xs font-bold transition-colors shadow-md active:scale-90"
                                [class.bg-blue-400]="gamepadButtons()['X'] || virtualPressed()['x']"
                                [class.bg-blue-600]="!gamepadButtons()['X'] && !virtualPressed()['x']"
                                [class.scale-95]="gamepadButtons()['X'] || virtualPressed()['x']"
                                (mousedown)="onVirtualButtonDown('x')"
                                (mouseup)="onVirtualButtonUp('x')"
                                (mouseleave)="onVirtualButtonUp('x')"
                                (touchstart)="onVirtualButtonDown('x'); $event.preventDefault()"
                                (touchend)="onVirtualButtonUp('x')">
                          X
                        </button>
                        <!-- B (right) - Close/Back -->
                        <button class="absolute right-0 top-1/2 -translate-y-1/2 w-8 h-8 rounded-full text-xs font-bold transition-colors shadow-md active:scale-90"
                                [class.bg-red-400]="gamepadButtons()['B'] || virtualPressed()['b']"
                                [class.bg-red-600]="!gamepadButtons()['B'] && !virtualPressed()['b']"
                                [class.scale-95]="gamepadButtons()['B'] || virtualPressed()['b']"
                                (click)="onVirtualButtonPress('b')">
                          B
                        </button>
                      </div>

                      <!-- Right Analog Stick -->
                      <app-virtual-joystick
                        [size]="80"
                        [knobSize]="40"
                        [externalPosition]="physicalRightStick()"
                        (positionChange)="onRightStickChange($event)">
                      </app-virtual-joystick>
                    </div>

                    <!-- Spacer -->
                    <div class="h-6"></div>
                  </div>

                </div>
              </div>
            </div>
          }
        </div>
      </footer>
    </div>
  `
})
export class AppComponent {
  activePanel = signal<string | null>(null);
  leftStick = signal<JoystickPosition>({ x: 0, y: 0 });
  rightStick = signal<JoystickPosition>({ x: 0, y: 0 });
  virtualPressed = signal<Record<string, boolean>>({});

  // Track which button is being held for hold-mode panels
  private heldButton = signal<DigitalInput | null>(null);

  // Gamepad state from physical controller
  gamepadConnected = computed(() => this.inputService.isGamepadConnected());
  gamepadName = computed(() => this.inputService.gamepad().name);
  physicalLeftStick = computed(() => this.inputService.gamepad().leftStick);
  physicalRightStick = computed(() => this.inputService.gamepad().rightStick);
  gamepadButtons = computed(() => this.inputService.gamepad().buttons);
  leftTrigger = computed(() => this.inputService.gamepad().leftTrigger);
  rightTrigger = computed(() => this.inputService.gamepad().rightTrigger);

  // Check if a preset panel is currently active
  presetPanelActive = computed(() => this.bindingsService.activePanelState().activePanelId !== null);

  constructor(
    public connectionService: ConnectionService,
    public inputService: InputService,
    public bindingsService: BindingsService
  ) {}

  /**
   * Handle virtual button press (mousedown/touchstart) from onscreen controls
   */
  onVirtualButtonDown(button: DigitalInput): void {
    console.log('Virtual button down:', button);

    // Visual feedback - show button as pressed
    this.virtualPressed.update(state => ({ ...state, [button]: true }));

    // Find the binding for this button
    const profile = this.bindingsService.activeProfile();
    if (!profile) {
      console.log('No active profile found!');
      return;
    }

    // Check for both 'press' and 'hold' triggers
    const pressBinding = profile.digitalBindings.find(
      b => b.input === button && b.trigger === 'press' && b.enabled
    );
    const holdBinding = profile.digitalBindings.find(
      b => b.input === button && b.trigger === 'hold' && b.enabled
    );

    // Determine panel activation mode from settings
    const panelActivation = profile.settings.panelActivation || 'press';

    // If this is a show_panel action, handle based on activation mode
    if (pressBinding?.action.type === 'show_panel' || holdBinding?.action.type === 'show_panel') {
      const binding = holdBinding || pressBinding;
      if (!binding || binding.action.type !== 'show_panel') return;

      const panelId = binding.action.panel_id;

      if (panelActivation === 'hold') {
        // Hold mode: show panel now, will hide on release
        this.heldButton.set(button);
        this.bindingsService.showPanel(panelId);
      } else {
        // Press mode: toggle panel (press again to close)
        this.bindingsService.togglePanel(panelId);
      }
      return;
    }

    // For non-panel actions, execute on press
    if (pressBinding) {
      this.executeDigitalAction(pressBinding.action);
    }
  }

  /**
   * Handle virtual button release (mouseup/touchend) from onscreen controls
   */
  onVirtualButtonUp(button: DigitalInput): void {
    console.log('Virtual button up:', button);

    // Visual feedback - show button as released
    this.virtualPressed.update(state => ({ ...state, [button]: false }));

    // Check if this was a held button for hold-mode panel
    if (this.heldButton() === button) {
      const profile = this.bindingsService.activeProfile();
      const panelActivation = profile?.settings.panelActivation || 'press';

      if (panelActivation === 'hold') {
        // Hide the panel when button is released in hold mode
        this.bindingsService.hidePanel();
      }
      this.heldButton.set(null);
    }
  }

  /**
   * Handle virtual button click (for simple press actions like navigation)
   */
  onVirtualButtonPress(button: DigitalInput): void {
    this.onVirtualButtonDown(button);
    // Auto-release after a short delay for click events
    setTimeout(() => this.onVirtualButtonUp(button), 150);
  }

  /**
   * Execute a digital action from a binding
   */
  private executeDigitalAction(action: typeof this.bindingsService.activeProfile extends () => infer P ? P extends { digitalBindings: { action: infer A }[] } ? A : never : never): void {
    switch (action.type) {
      case 'show_panel':
        this.bindingsService.showPanel(action.panel_id);
        break;
      case 'hide_panel':
        this.bindingsService.hidePanel();
        break;
      case 'navigate_panel':
        this.bindingsService.navigatePanel(action.direction);
        break;
      case 'select_panel_item':
        this.bindingsService.selectCurrentItem();
        break;
      case 'activate_preset':
        this.bindingsService.activatePreset(action.preset_id);
        break;
      case 'e_stop':
        this.emergencyStop();
        break;
      case 'toggle_output':
        console.log('Toggle output:', action.target_id);
        // TODO: Implement toggle output
        break;
      case 'cycle_output':
        console.log('Cycle output:', action.target_id, action.values);
        // TODO: Implement cycle output
        break;
      case 'direct_control':
        console.log('Direct control:', action.target, action.value);
        // TODO: Send command to server
        break;
      case 'none':
        break;
    }
  }

  onLeftStickChange(position: JoystickPosition): void {
    this.leftStick.set(position);
    // TODO: Send control command based on left stick position
    console.log('Left stick:', position);
  }

  onRightStickChange(position: JoystickPosition): void {
    this.rightStick.set(position);
    // TODO: Send control command based on right stick position
    console.log('Right stick:', position);
  }

  togglePanel(panel: string): void {
    if (this.activePanel() === panel) {
      this.activePanel.set(null);
    } else {
      this.activePanel.set(panel);
    }
  }

  getTabClass(panel: string): string {
    const base = 'border-r border-saint-surface-light';
    if (this.activePanel() === panel) {
      return `${base} bg-saint-primary text-white`;
    }
    return `${base} hover:bg-saint-surface-light text-saint-text-muted`;
  }

  getStatusClass(): string {
    const base = 'status-indicator';
    switch (this.connectionService.status()) {
      case ConnectionStatus.Connected:
        return `${base} status-connected`;
      case ConnectionStatus.Connecting:
        return `${base} status-connecting`;
      default:
        return `${base} status-disconnected`;
    }
  }

  getStatusText(): string {
    switch (this.connectionService.status()) {
      case ConnectionStatus.Connected:
        return 'Connected';
      case ConnectionStatus.Connecting:
        return 'Connecting...';
      case ConnectionStatus.Authenticating:
        return 'Authenticating...';
      default:
        return 'Disconnected';
    }
  }

  async emergencyStop(): Promise<void> {
    try {
      await this.connectionService.emergencyStop();
    } catch (err) {
      console.error('Emergency stop failed:', err);
    }
  }
}

// controller/src/App.vue
<!--
    Root shell. Header (nav OR active-panel chrome + connection
    dropdown + E-Stop), e-stop banner, main (router-outlet OR
    preset-panel overlay), and the virtual keyboard overlay.
    Battery/WiFi live on the Dashboard tab; on-screen controls were
    removed (physical gamepad only).
-->
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { RouterLink, RouterView } from 'vue-router';
import PresetPanel from './components/PresetPanel.vue';
import VirtualKeyboard from './components/VirtualKeyboard.vue';
import { useConnection, ConnectionStatus } from './composables/useConnection';
import { useInput, type ButtonEvent } from './composables/useInput';
import { useBindings, type DigitalInput, type DigitalAction } from './composables/useBindings';
import { useKeyboard } from './composables/useKeyboard';
import { useLibrary } from './composables/useLibrary';

const conn = useConnection();
const input = useInput();
const bindings = useBindings();
const keyboard = useKeyboard();
const library = useLibrary();

// ─── Reactive state ──────────────────────────────────────────────────

// Written by the physical-button handlers; kept for hold-mode tracking.
const virtualPressed = ref<Record<string, boolean>>({});
let heldButton: DigitalInput | null = null;

// Hardware-button-name → DigitalInput key. Keeps the binding lookup
// keyed on canonical short names while the gamepad poll emits whatever
// the platform reports.
const buttonMap: Record<string, DigitalInput> = {
    A: 'a', B: 'b', X: 'x', Y: 'y',
    LB: 'lb', RB: 'rb',
    DPadUp: 'd_pad_up', DPadDown: 'd_pad_down',
    DPadLeft: 'd_pad_left', DPadRight: 'd_pad_right',
    Start: 'start', Select: 'select',
    LeftStick: 'left_stick', RightStick: 'right_stick',
    L4: 'l4', R4: 'r4', L5: 'l5', R5: 'r5', Steam: 'steam',
};

// ─── Connection dropdown + active-panel header state ─────────────────
const connMenuOpen = ref(false);

// The preset panel currently open drives the header's icon/name/color.
// The group dropdown that used to live here is gone: choosing a source
// is the panel's own source list now (PresetPanel), which can show every
// playlist at once with its item count instead of hiding them behind a
// closed select.
const headerPanel = computed(() => bindings.activePanel.value);

function connDotClass(): string {
    switch (conn.status.value) {
        case ConnectionStatus.Connected:      return 'text-saint-success';
        case ConnectionStatus.Connecting:
        case ConnectionStatus.Authenticating: return 'text-yellow-500';
        default:                              return 'text-red-500';
    }
}

async function onReconnect(): Promise<void> {
    connMenuOpen.value = false;
    try { await conn.reconnect(); }
    catch (err) { console.error('Reconnect failed:', err); }
}

const presetPanelActive = computed(() =>
    bindings.activePanelState.value.activePanelId !== null);

// ─── Status display ──────────────────────────────────────────────────

function getStatusText(): string {
    switch (conn.status.value) {
        case ConnectionStatus.Connected:     return 'Connected';
        case ConnectionStatus.Connecting:    return 'Connecting...';
        case ConnectionStatus.Authenticating: return 'Authenticating...';
        default:                             return 'Disconnected';
    }
}

async function emergencyStop(): Promise<void> {
    try { await conn.emergencyStop(); }
    catch (err) { console.error('Emergency stop failed:', err); }
}

// ─── Binding-action execution ────────────────────────────────────────

function executeDigitalAction(action: DigitalAction): void {
    switch (action.type) {
        case 'show_panel':       bindings.showPanel(action.panel_id, action.default_group, action.keep_open); break;
        case 'hide_panel':       bindings.hidePanel(); break;
        case 'navigate_panel':   bindings.navigatePanel(action.direction); break;
        case 'select_panel_item': bindings.selectCurrentItem(); break;
        case 'activate_preset':  void bindings.activatePreset(action.preset_id); break;
        case 'e_stop':           void emergencyStop(); break;
        case 'toggle_output':    console.log('Toggle output:', action.target_id); break;
        case 'cycle_output':     console.log('Cycle output:', action.target_id, action.values); break;
        case 'direct_control':   console.log('Direct control:', action.target, action.value); break;
        case 'none':             break;
    }
}

function onVirtualButtonDown(button: DigitalInput): void {
    virtualPressed.value = { ...virtualPressed.value, [button]: true };

    const profile = bindings.activeProfile.value;
    if (!profile) return;

    const pressBinding = profile.digitalBindings.find(
        b => b.input === button && b.trigger === 'press' && b.enabled);
    const holdBinding = profile.digitalBindings.find(
        b => b.input === button && b.trigger === 'hold' && b.enabled);

    const panelActivation = profile.settings.panelActivation || 'press';

    // show_panel actions: hold-mode shows on press + hides on release;
    // press-mode toggles.
    if (pressBinding?.action.type === 'show_panel' || holdBinding?.action.type === 'show_panel') {
        const binding = holdBinding || pressBinding;
        if (!binding || binding.action.type !== 'show_panel') return;
        const panelId = binding.action.panel_id;
        const defaultGroup = binding.action.default_group;
        const keepOpen = binding.action.keep_open;
        if (panelActivation === 'hold') {
            heldButton = button;
            bindings.showPanel(panelId, defaultGroup, keepOpen);
        } else {
            bindings.togglePanel(panelId, defaultGroup, keepOpen);
        }
        return;
    }

    if (pressBinding) {
        executeDigitalAction(pressBinding.action);
    }
}

function onVirtualButtonUp(button: DigitalInput): void {
    virtualPressed.value = { ...virtualPressed.value, [button]: false };

    if (heldButton === button) {
        const profile = bindings.activeProfile.value;
        const panelActivation = profile?.settings.panelActivation || 'press';
        if (panelActivation === 'hold') bindings.hidePanel();
        heldButton = null;
    }
}

function handleHardwareButton(event: ButtonEvent): void {
    const digitalInput = buttonMap[event.button];
    if (!digitalInput) return;

    // X is the Steam OSK trigger in Game Mode — when a text field is
    // focused, let Steam handle it instead of activating our binding.
    if (digitalInput === 'x' && keyboard.isTextFieldFocused()) return;

    if (event.pressed) onVirtualButtonDown(digitalInput);
    else onVirtualButtonUp(digitalInput);
}

// ─── Lifecycle ───────────────────────────────────────────────────────

let unsubButtons: (() => void) | null = null;

onMounted(() => {
    unsubButtons = input.onButtonEvent(handleHardwareButton);
});

onBeforeUnmount(() => {
    unsubButtons?.();
});
</script>

<template>
    <div class="h-screen flex flex-col">
        <!-- Header. When a preset panel is open the bar takes the panel's
             color and hosts the panel chrome (icon/name/group/page);
             otherwise it shows the app nav. -->
        <header class="border-b border-saint-surface-light px-4 py-3 flex items-center justify-between gap-4"
                :class="presetPanelActive ? 'text-white' : 'bg-saint-surface'"
                :style="presetPanelActive && headerPanel ? { background: headerPanel.color } : undefined">

            <!-- Left: nav (idle) or Back + preset identity (panel open) -->
            <div class="flex items-center gap-3 min-w-0">
                <template v-if="!presetPanelActive">
                    <nav class="flex gap-2">
                        <RouterLink to="/dashboard"
                                    class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors"
                                    active-class="bg-saint-primary">Dashboard</RouterLink>
                        <RouterLink to="/controller"
                                    class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors"
                                    active-class="bg-saint-primary">Controller</RouterLink>
                        <RouterLink to="/bindings"
                                    class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors"
                                    active-class="bg-saint-primary">Bindings</RouterLink>
                        <RouterLink to="/settings"
                                    class="px-3 py-1.5 rounded-lg text-sm hover:bg-saint-surface-light transition-colors"
                                    active-class="bg-saint-primary">Settings</RouterLink>
                    </nav>
                </template>
                <template v-else>
                    <button class="px-3 py-1.5 rounded-lg text-sm hover:bg-black/15 transition-colors flex items-center gap-2 shrink-0"
                            @click="bindings.hidePanel">
                        <span class="material-icons text-sm">arrow_back</span>
                        Back
                    </button>
                    <span v-if="headerPanel" class="material-symbols-outlined text-2xl shrink-0">{{ headerPanel.icon }}</span>
                    <h1 v-if="headerPanel" class="text-lg font-semibold truncate">{{ headerPanel.name }}</h1>
                </template>
            </div>

            <!-- Right: sync spinner, connection icon+dropdown, E-Stop -->
            <div class="flex items-center gap-4 shrink-0">
                <span v-if="library.syncing.value"
                      class="material-icons animate-spin text-lg leading-none opacity-70"
                      title="Syncing library…">sync</span>

                <!-- Connection: icon only; click for ping + reconnect. -->
                <div class="relative">
                    <button class="flex items-center p-1 rounded-lg hover:bg-black/15 transition-colors"
                            :title="getStatusText()"
                            @click="connMenuOpen = !connMenuOpen">
                        <span class="material-icons text-xl leading-none" :class="connDotClass()">
                            fiber_manual_record
                        </span>
                    </button>
                    <template v-if="connMenuOpen">
                        <!-- click-away backdrop -->
                        <div class="fixed inset-0 z-40" @click="connMenuOpen = false"></div>
                        <div class="absolute right-0 mt-2 w-52 z-50 bg-saint-surface text-saint-text border border-saint-surface-light rounded-lg shadow-lg p-3 space-y-2">
                            <div class="flex items-center justify-between text-sm">
                                <span class="text-saint-text-muted">Status</span>
                                <span :class="connDotClass()">{{ getStatusText() }}</span>
                            </div>
                            <div class="flex items-center justify-between text-sm">
                                <span class="text-saint-text-muted">Ping</span>
                                <span class="font-mono">{{ conn.pingMs.value === null ? '—' : conn.pingMs.value + ' ms' }}</span>
                            </div>
                            <button class="w-full mt-1 px-3 py-1.5 rounded-lg text-sm bg-saint-primary hover:bg-blue-600 text-white flex items-center justify-center gap-2 transition-colors"
                                    @click="onReconnect">
                                <span class="material-icons text-sm">refresh</span> Reconnect
                            </button>
                        </div>
                    </template>
                </div>

                <!-- E-Stop -->
                <button :class="conn.estopActive.value
                            ? 'flex items-center gap-2 px-4 py-2 bg-amber-500 hover:bg-amber-600 text-black font-semibold rounded-lg transition-colors uppercase tracking-wide ring-2 ring-amber-300'
                            : 'flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-colors uppercase tracking-wide'"
                        :title="conn.estopActive.value ? 'E-Stop is ENGAGED — press to release' : 'Emergency Stop'"
                        @click="emergencyStop">
                    <span class="material-icons icon-sm">
                        {{ conn.estopActive.value ? 'check_circle' : 'front_hand' }}
                    </span>
                    <span>{{ conn.estopActive.value ? 'Release' : 'E-Stop' }}</span>
                </button>
            </div>
        </header>

        <!-- System-wide E-Stop banner. The Rust client and the
             server's routing evaluator both block control inputs
             while engaged — this is visual confirmation. -->
        <div v-if="conn.estopActive.value"
             class="bg-amber-500 text-black px-4 py-2 text-center text-sm font-semibold flex items-center justify-center gap-2">
            <span class="material-icons icon-sm">warning</span>
            EMERGENCY STOP ENGAGED — control inputs are suppressed system-wide.
            Press the E-Stop button to release.
        </div>

        <!-- Main: router-outlet or preset-panel overlay -->
        <main class="flex-1 overflow-hidden">
            <PresetPanel v-if="presetPanelActive" />
            <div v-else class="h-full overflow-auto touch-scroll">
                <RouterView />
            </div>
        </main>


        <!-- Virtual Keyboard overlay -->
        <VirtualKeyboard />
    </div>
</template>
